### ISSUE TITLE
Notifications are sent out too early

### ISSUE THREAD

**Issue by jl-digital** [doublesecretagency/craft-notifier#18]
When the message hits the inbox and you'll immediately click the link to the entry, you're presented with a 404 page.
I guess it gets sent beforeSave and not after? It looks like the entry is not done saving and propagating when the notification gets sent out.

**Comment by lindseydiloreto** [comment]
Try updating to [v1.0](https://github.com/doublesecretagency/craft-notifier/releases/tag/1.0.0), which was released yesterday.

Notifications will be triggered by the `Entry::EVENT_AFTER_PROPAGATE` event, which guarantees that the Entry is completely saved and propagated before the notification goes out.

https://github.com/doublesecretagency/craft-notifier/blob/47ad1e8ea03c107ea8bd3ccb6c63abab36258dbc/src/services/Events.php#L83-L109
