### ISSUE TITLE
Feature Request: Notification Labels

### ISSUE THREAD

**Issue by johnj24** [doublesecretagency/craft-notifier#8]
Having the ability to add labels or titles to each notification will help me reference them when I come back to edit or add new triggers.

**Comment by lindseydiloreto** [comment]
That's a great idea, thanks @johnj24!

**Comment by lindseydiloreto** [comment]
This is now possible in [v1.0](https://github.com/doublesecretagency/craft-notifier/releases/tag/1.0.0), with the conversion to [Notification Elements](https://plugins.doublesecretagency.com/notifier/elements). 👍
